---
- name: Check service versions
  hosts: all
  gather_facts: no
  tasks:
    - name: SSH into the server and check service versions
      ansible.builtin.shell: cat /opt/{{ service }}/VERSION
      register: service_version
      delegate_to: "{{ inventory_hostname }}"
      with_items: "{{ services }}"
      loop_control:
        loop_var: service_info

    - name: Display service versions
      ansible.builtin.debug:
        msg: "Service {{ service_info.item }} version: {{ item.stdout }}"
      with_items: "{{ service_version.results }}"
      loop_control:
        loop_var: item
